name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    
    - uses: actions/cache@v1
      with:
        path: /nix/store
        key: ${{basename -s .drv $(nix-instantiate ./shell.nix)}}

    - name: Build
      run: nix-shell --pure --run make
    
    - uses: actions/upload-artifact@v2-preview
      with:
        name: paper
        path: paper.pdf
