name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    
    - uses: actions/download-artifact@v1
      with:
        name: closure
        
    - name: Load closure
      run: test -f paper.closure && nix-store --import < paper.closure

    - name: Build
      run: nix-shell --pure --run make
    
    - name: Save closure
      run: nix-store --export $(nix-store -qR $(nix-build -E '(import ./shell.nix).buildInputs')) > paper.closure
        
    - uses: actions/upload-artifact@v2-preview
      with:
        name: closure
        path: paper.closure
    
    - uses: actions/upload-artifact@v2-preview
      with:
        name: paper
        path: paper.pdf
