name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7

    - name: Build
      run: nix-shell --pure --run make
    
    - uses: actions/upload-artifact@v1
      with:
        name: paper
        path: paper.pdf
