name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    
    - uses: actions/cache@v1
      id: cache
      with:
        path: cache
        key: ${{runner.os}}-closure
        
    - name: Load closure
      if: steps.cache.outputs.cache-hit == 'true'
      run: nix-store --import < cache/paper.closure

    - name: Build
      run: nix-shell --pure --run make
    
    - name: Save closure
      run: |
        mkdir -p cache
        nix-store --export $(nix-store -qR $(nix-instantiate ./shell.nix)) > cache/paper.closure
    
    - uses: actions/upload-artifact@v2-preview
      with:
        name: paper
        path: paper.pdf
